VISIBILITY_PRIVATE = "private"
VISIBILITY_LINK_ONLY = "link_only"
VISIBILITY_PUBLIC = "public"
VISIBILITY_FOLLOWERS = "followers"
VISIBILITY_VALUES = (
    VISIBILITY_PRIVATE,
    VISIBILITY_LINK_ONLY,
    VISIBILITY_PUBLIC,
    VISIBILITY_FOLLOWERS,
)

SOURCE_FILE_STATUS_UPLOADED = "uploaded"
SOURCE_FILE_STATUS_PARSED = "parsed"
SOURCE_FILE_STATUS_COMMITTED = "committed"
SOURCE_FILE_STATUS_FAILED = "failed"
SOURCE_FILE_STATUS_VALUES = (
    SOURCE_FILE_STATUS_UPLOADED,
    SOURCE_FILE_STATUS_PARSED,
    SOURCE_FILE_STATUS_COMMITTED,
    SOURCE_FILE_STATUS_FAILED,
)

UPLOAD_REVIEW_STATUS_PENDING = "pending"
UPLOAD_REVIEW_STATUS_NEEDS_REVIEW = "needs_review"
UPLOAD_REVIEW_STATUS_READY = "ready"
UPLOAD_REVIEW_STATUS_COMMITTED = "committed"
UPLOAD_REVIEW_STATUS_FAILED = "failed"
UPLOAD_REVIEW_STATUS_VALUES = (
    UPLOAD_REVIEW_STATUS_PENDING,
    UPLOAD_REVIEW_STATUS_NEEDS_REVIEW,
    UPLOAD_REVIEW_STATUS_READY,
    UPLOAD_REVIEW_STATUS_COMMITTED,
    UPLOAD_REVIEW_STATUS_FAILED,
)

COMPUTED_STATUS_DRAFT = "draft"
COMPUTED_STATUS_PENDING = "pending"
COMPUTED_STATUS_READY = "ready"
COMPUTED_STATUS_STALE = "stale"
COMPUTED_STATUS_FAILED = "failed"
COMPUTED_STATUS_VALUES = (
    COMPUTED_STATUS_DRAFT,
    COMPUTED_STATUS_PENDING,
    COMPUTED_STATUS_READY,
    COMPUTED_STATUS_STALE,
    COMPUTED_STATUS_FAILED,
)
