EXPECTED_SCORE_MIN_SAMPLES = 2
EXPECTED_SCORE_MIN_SAMPLES_BY_LEVEL = {
    "full": 3,
    "no_par": 3,
    "no_distance": 2,
    "start_category": 2,
    "start_only": 1,
}
EXPECTED_SCORE_RECENCY_DECAY = 0.9

TEE_STRATEGY_MIN_SAMPLES = 3
APPROACH_STRATEGY_MIN_SAMPLES = 3
CLUB_RELIABILITY_MIN_SAMPLES = 5

RECOMMENDATION_SAMPLE_HIGH_WATERMARK = 30
RECOMMENDATION_SAMPLE_MEDIUM_WATERMARK = 15
